 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stand_ups", type: :request do
  # StandUp. As you add validations to StandUp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StandUp.create! valid_attributes
      get stand_ups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stand_up = StandUp.create! valid_attributes
      get stand_up_url(stand_up)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stand_up_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      stand_up = StandUp.create! valid_attributes
      get edit_stand_up_url(stand_up)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StandUp" do
        expect {
          post stand_ups_url, params: { stand_up: valid_attributes }
        }.to change(StandUp, :count).by(1)
      end

      it "redirects to the created stand_up" do
        post stand_ups_url, params: { stand_up: valid_attributes }
        expect(response).to redirect_to(stand_up_url(StandUp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StandUp" do
        expect {
          post stand_ups_url, params: { stand_up: invalid_attributes }
        }.to change(StandUp, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post stand_ups_url, params: { stand_up: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stand_up" do
        stand_up = StandUp.create! valid_attributes
        patch stand_up_url(stand_up), params: { stand_up: new_attributes }
        stand_up.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stand_up" do
        stand_up = StandUp.create! valid_attributes
        patch stand_up_url(stand_up), params: { stand_up: new_attributes }
        stand_up.reload
        expect(response).to redirect_to(stand_up_url(stand_up))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        stand_up = StandUp.create! valid_attributes
        patch stand_up_url(stand_up), params: { stand_up: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stand_up" do
      stand_up = StandUp.create! valid_attributes
      expect {
        delete stand_up_url(stand_up)
      }.to change(StandUp, :count).by(-1)
    end

    it "redirects to the stand_ups list" do
      stand_up = StandUp.create! valid_attributes
      delete stand_up_url(stand_up)
      expect(response).to redirect_to(stand_ups_url)
    end
  end
end
